server:
  port: 8081

spring:
  application:
    name: rxqwkj-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}


